//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peanut {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataMsg() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peanut.DataMsg", typeof(DataMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 业务对象{0}和数据对象{1}没有可匹配属性! 的本地化字符串。
        /// </summary>
        internal static string BOBJ_NOTMATCH_DOBJ {
            get {
                return ResourceManager.GetString("BOBJ_NOTMATCH_DOBJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}不存在{1}描述! 的本地化字符串。
        /// </summary>
        internal static string COLUMN_DESC_NOTFOUND {
            get {
                return ResourceManager.GetString("COLUMN_DESC_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法数据库连接串描述! 的本地化字符串。
        /// </summary>
        internal static string CONNECTION_STRING_ERROR {
            get {
                return ResourceManager.GetString("CONNECTION_STRING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}数据库配置信息不存在! 的本地化字符串。
        /// </summary>
        internal static string DATABASE_SETTING_NOTFOUND {
            get {
                return ResourceManager.GetString("DATABASE_SETTING_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在ID映射信息,不能进行数据获取操作! 的本地化字符串。
        /// </summary>
        internal static string ID_MAP_NOTFOUND {
            get {
                return ResourceManager.GetString("ID_MAP_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}没有实现实体类型描述! 的本地化字符串。
        /// </summary>
        internal static string OBJECT_MAPPING_NOTFOUND {
            get {
                return ResourceManager.GetString("OBJECT_MAPPING_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}对象不存在表描述信息! 的本地化字符串。
        /// </summary>
        internal static string OBJECT_NOT_MAPTOTABLE {
            get {
                return ResourceManager.GetString("OBJECT_NOT_MAPTOTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}并没有实现IEntityState! 的本地化字符串。
        /// </summary>
        internal static string OBJECT_NOTIMPL_IENTITYSTATE {
            get {
                return ResourceManager.GetString("OBJECT_NOTIMPL_IENTITYSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}对象没有存储过程描述信息! 的本地化字符串。
        /// </summary>
        internal static string OBJECT_PROCDESC_NOTFOUND {
            get {
                return ResourceManager.GetString("OBJECT_PROCDESC_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象不存在可更新信息! 的本地化字符串。
        /// </summary>
        internal static string OBJECT_UPDATA_NOTFOUND {
            get {
                return ResourceManager.GetString("OBJECT_UPDATA_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据查询不存在{0}字段! 的本地化字符串。
        /// </summary>
        internal static string READER_COLUMN_NOFOUND {
            get {
                return ResourceManager.GetString("READER_COLUMN_NOFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}字段值到{1}属性转换错误! 的本地化字符串。
        /// </summary>
        internal static string READER_TO_PROPERTY_ERROR {
            get {
                return ResourceManager.GetString("READER_TO_PROPERTY_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}重复描述{1}字段! 的本地化字符串。
        /// </summary>
        internal static string REPEATE_DESC_FIELD {
            get {
                return ResourceManager.GetString("REPEATE_DESC_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}重复描述ID! 的本地化字符串。
        /// </summary>
        internal static string REPEATE_DESC_ID {
            get {
                return ResourceManager.GetString("REPEATE_DESC_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不存在ID映射信息,不能进行数据更新操作! 的本地化字符串。
        /// </summary>
        internal static string UPDATE_ERROR_ID_NOTFOUND {
            get {
                return ResourceManager.GetString("UPDATE_ERROR_ID_NOTFOUND", resourceCulture);
            }
        }
    }
}
